extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_stone_lights;
extern Lights1 ccm_dl_wall_lights;
extern Lights1 ccm_dl_rock_lights;
extern Lights1 ccm_dl_grass_lights;
extern u8 ccm_dl_bob_textures_03000_rgba16_i8[];
extern u8 ccm_dl_bob_textures_02000_rgba16_ci8[];
extern u8 ccm_dl_bob_textures_02000_rgba16_ci8_pal_rgba16[];
extern u8 ccm_dl_wf_textures_05000_rgba16_ci8[];
extern u8 ccm_dl_wf_textures_05000_rgba16_ci8_pal_rgba16[];
extern u8 ccm_dl_wf_textures_05800_rgba16_ci8[];
extern u8 ccm_dl_wf_textures_05800_rgba16_ci8_pal_rgba16[];
extern Vtx ccm_dl_base_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_base_mesh_layer_1_vtx_0[328];
extern Gfx ccm_dl_base_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_base_mesh_layer_1_vtx_1[12];
extern Gfx ccm_dl_base_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_castle_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_castle_mesh_layer_1_vtx_0[20];
extern Gfx ccm_dl_castle_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_castle_mesh_layer_1_vtx_1[6];
extern Gfx ccm_dl_castle_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_stone[];
extern Gfx mat_ccm_dl_wall[];
extern Gfx mat_revert_ccm_dl_wall[];
extern Gfx mat_ccm_dl_rock[];
extern Gfx mat_revert_ccm_dl_rock[];
extern Gfx mat_ccm_dl_grass[];
extern Gfx mat_revert_ccm_dl_grass[];
extern Gfx ccm_dl_base_mesh_layer_1[];
extern Gfx ccm_dl_castle_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
