extern const GeoLayout totwc_area_1_geo[];
extern const GeoLayout totwc_area_1[];
extern const Collision totwc_area_1_collision[];
extern const MacroObject totwc_area_1_macro_objs[];
extern Lights1 totwc_dl_stone_lights;
extern Lights1 totwc_dl_clouds_lights;
extern Lights1 totwc_dl_haze_lights;
extern Lights1 totwc_dl_roof_lights;
extern Lights1 totwc_dl_window_lights;
extern u8 totwc_dl__1_rgba16_i8[];
extern u8 totwc_dl_cloudy_ia8[];
extern u8 totwc_dl__3_ia16_ia8[];
extern u8 totwc_dl__2_rgba16_i8[];
extern u8 totwc_dl__0_rgba16_ci8[];
extern u8 totwc_dl__0_rgba16_ci8_pal_rgba16[];
extern Vtx totwc_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx totwc_dl_Cylinder_mesh_layer_1_vtx_0[60];
extern Gfx totwc_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx totwc_dl_Icosphere_mesh_layer_4_vtx_cull[8];
extern Vtx totwc_dl_Icosphere_mesh_layer_4_vtx_0[74];
extern Gfx totwc_dl_Icosphere_mesh_layer_4_tri_0[];
extern Vtx totwc_dl_Icosphere_001_mesh_layer_5_vtx_cull[8];
extern Vtx totwc_dl_Icosphere_001_mesh_layer_5_vtx_0[81];
extern Gfx totwc_dl_Icosphere_001_mesh_layer_5_tri_0[];
extern Vtx totwc_dl_tower_mesh_layer_1_vtx_cull[8];
extern Vtx totwc_dl_tower_mesh_layer_1_vtx_0[16];
extern Gfx totwc_dl_tower_mesh_layer_1_tri_0[];
extern Vtx totwc_dl_tower_mesh_layer_1_vtx_1[32];
extern Gfx totwc_dl_tower_mesh_layer_1_tri_1[];
extern Vtx totwc_dl_tower_mesh_layer_1_vtx_2[20];
extern Gfx totwc_dl_tower_mesh_layer_1_tri_2[];
extern Gfx mat_totwc_dl_stone[];
extern Gfx mat_totwc_dl_clouds[];
extern Gfx mat_revert_totwc_dl_clouds[];
extern Gfx mat_totwc_dl_haze[];
extern Gfx mat_revert_totwc_dl_haze[];
extern Gfx mat_totwc_dl_roof[];
extern Gfx mat_totwc_dl_window[];
extern Gfx mat_revert_totwc_dl_window[];
extern Gfx totwc_dl_Cylinder_mesh_layer_1[];
extern Gfx totwc_dl_Icosphere_mesh_layer_4[];
extern Gfx totwc_dl_Icosphere_001_mesh_layer_5[];
extern Gfx totwc_dl_tower_mesh_layer_1[];
extern Gfx totwc_dl_material_revert_render_settings[];
