extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const Trajectory bob_area_1_spline_saw_blade1_path[];
extern u8 bob_dl_E000810_ia8[];
extern u8 bob_dl_E005810_i8[];
extern Vtx bob_dl_Floor_mesh_layer_5_vtx_0[22];
extern Gfx bob_dl_Floor_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Floor_mesh_layer_1_vtx_0[84];
extern Gfx bob_dl_Floor_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_0[38];
extern Gfx bob_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[220];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_grate[];
extern Gfx mat_revert_bob_dl_grate[];
extern Gfx mat_bob_dl_walkway[];
extern Gfx mat_revert_bob_dl_walkway[];
extern Gfx bob_dl_Floor_mesh_layer_5[];
extern Gfx bob_dl_Floor_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
