extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bob_area_1_spline_camSpline0[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bob_area_2_spline_camSpline1_focus[];
extern struct CutsceneSplinePoint bob_area_2_spline_camSpline1_pos[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern Vtx bob_dl_camSpline1_pos_mesh_001_mesh_layer_1_vtx_0[2278];
extern Gfx bob_dl_camSpline1_pos_mesh_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_floor_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_floor_mesh_layer_1_tri_0[];
extern Vtx bob_dl_camSpline1_focus_mesh_mesh_layer_1_vtx_0[1948];
extern Gfx bob_dl_camSpline1_focus_mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_camSpline1_pos_mesh_mesh_layer_1_vtx_0[2278];
extern Gfx bob_dl_camSpline1_pos_mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_floor1_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_floor1_mesh_layer_1_tri_0[];
extern Vtx bob_dl_floor2_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_floor2_mesh_layer_1_tri_0[];
extern Vtx bob_dl_floor3_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_floor3_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_red[];
extern Gfx mat_revert_bob_dl_red[];
extern Gfx mat_bob_dl_grass[];
extern Gfx mat_revert_bob_dl_grass[];
extern Gfx mat_bob_dl_blue[];
extern Gfx mat_revert_bob_dl_blue[];
extern Gfx bob_dl_camSpline1_pos_mesh_001_mesh_layer_1[];
extern Gfx bob_dl_floor_mesh_layer_1[];
extern Gfx bob_dl_camSpline1_focus_mesh_mesh_layer_1[];
extern Gfx bob_dl_camSpline1_pos_mesh_mesh_layer_1[];
extern Gfx bob_dl_floor1_mesh_layer_1[];
extern Gfx bob_dl_floor2_mesh_layer_1[];
extern Gfx bob_dl_floor3_mesh_layer_1[];
