extern const GeoLayout saw_blade_geo[];
extern u8 saw_blade_metal3_i8[];
extern u8 saw_blade_metal1_i8[];
extern Vtx saw_blade_SawBlade_mesh_layer_1_vtx_0[32];
extern Gfx saw_blade_SawBlade_mesh_layer_1_tri_0[];
extern Vtx saw_blade_SawBlade_mesh_layer_1_vtx_1[76];
extern Gfx saw_blade_SawBlade_mesh_layer_1_tri_1[];
extern Gfx mat_saw_blade_saw_body[];
extern Gfx mat_revert_saw_blade_saw_body[];
extern Gfx mat_saw_blade_blades[];
extern Gfx mat_revert_saw_blade_blades[];
extern Gfx saw_blade_SawBlade_mesh_layer_1[];
