extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern Lights1 wf_dl_rock_lights;
extern Lights1 wf_dl_grass_lights;
extern u8 wf_dl_wf_textures_05000_rgba16_ci8[];
extern u8 wf_dl_wf_textures_05000_rgba16_ci8_pal_rgba16[];
extern u8 wf_dl_wf_textures_05800_rgba16_ci8[];
extern u8 wf_dl_wf_textures_05800_rgba16_ci8_pal_rgba16[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_0[40];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_1[14];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cylinder_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cylinder_001_mesh_layer_1_vtx_0[40];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_001_mesh_layer_1_vtx_1[14];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1_tri_1[];
extern Gfx mat_wf_dl_rock[];
extern Gfx mat_revert_wf_dl_rock[];
extern Gfx mat_wf_dl_grass[];
extern Gfx mat_revert_wf_dl_grass[];
extern Gfx wf_dl_Cylinder_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
